// <auto-generated />
using System;
using IBuy.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IBuy.API.Migrations
{
    [DbContext(typeof(IBuyDbContext))]
    [Migration("20250425080406_AddCreditCardAndIbanToCustomerDetas")]
    partial class AddCreditCardAndIbanToCustomerDetas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IBuy.API.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9fdfcfb3-54f0-4707-bf4b-3cf8e87efaa9"),
                            Description = "Bellezza e cura personale",
                            Name = "Cosmetici"
                        },
                        new
                        {
                            Id = new Guid("2ed3f445-d087-4f76-a3e7-9c278dc160c1"),
                            Description = "Dispositivi elettronici",
                            Name = "Tecnologia"
                        },
                        new
                        {
                            Id = new Guid("e4c3b1ee-419a-41e4-a3c2-c173509a81de"),
                            Description = "Casa e cucina",
                            Name = "Elettrodomestici"
                        },
                        new
                        {
                            Id = new Guid("f83c2b7e-1d2e-4c1f-a51f-8b745f4e5b9b"),
                            Description = "Moda uomo e donna",
                            Name = "Abbigliamento"
                        },
                        new
                        {
                            Id = new Guid("21f3cb15-5054-4a3a-8752-f26262ff0e88"),
                            Description = "Hobby e tempo libero",
                            Name = "Tempo libero"
                        },
                        new
                        {
                            Id = new Guid("adbf2d17-62c6-44a7-a6d7-d09d510674c5"),
                            Description = "Sport e outdoor",
                            Name = "Attrezzatura sportiva"
                        },
                        new
                        {
                            Id = new Guid("ab73a4ea-76fd-41cb-8a4d-4b0e9b610e38"),
                            Description = "Prodotti per animali",
                            Name = "Amici animali"
                        });
                });

            modelBuilder.Entity("IBuy.API.Models.CustomerDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cap")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreditCard")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("DiscountCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IBAN")
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CustomerDetails");
                });

            modelBuilder.Entity("IBuy.API.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBestSeller")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Producer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1c62e4d-bfe5-41ae-9050-e3c1e2f10dce"),
                            CategoryId = new Guid("9fdfcfb3-54f0-4707-bf4b-3cf8e87efaa9"),
                            Description = "Crema giorno nutriente",
                            Image = "images/CremaIdratante.jpg",
                            IsBestSeller = true,
                            Name = "Crema Idratante",
                            Price = 14.99m,
                            Producer = "L'Oreal",
                            Quantity = 60
                        },
                        new
                        {
                            Id = new Guid("87f51894-f013-4dc4-bc7c-761f74b12389"),
                            CategoryId = new Guid("9fdfcfb3-54f0-4707-bf4b-3cf8e87efaa9"),
                            Description = "Effetto ciglia finte",
                            Image = "images/MascaraVolume.jpg",
                            IsBestSeller = true,
                            Name = "Mascara Volume",
                            Price = 12.50m,
                            Producer = "Maybelline",
                            Quantity = 40
                        },
                        new
                        {
                            Id = new Guid("3484e37c-4fd7-42e2-938c-1d82ad7d41ef"),
                            CategoryId = new Guid("2ed3f445-d087-4f76-a3e7-9c278dc160c1"),
                            Description = "Display AMOLED e 128GB",
                            Image = "images/Smartphone_X100.jpg",
                            IsBestSeller = true,
                            Name = "Smartphone X100",
                            Price = 399.99m,
                            Producer = "TechBrand",
                            Quantity = 40
                        },
                        new
                        {
                            Id = new Guid("120aaf6e-ff2d-4d3c-bf56-cf4b47c5b4b0"),
                            CategoryId = new Guid("2ed3f445-d087-4f76-a3e7-9c278dc160c1"),
                            Description = "Noise cancelling",
                            Image = "images/CuffieWireless.jpg",
                            IsBestSeller = false,
                            Name = "Cuffie Wireless",
                            Price = 59.99m,
                            Producer = "SoundMax",
                            Quantity = 60
                        },
                        new
                        {
                            Id = new Guid("b5f80fd2-c270-4cd5-9ef2-1c9d4fc0b18f"),
                            CategoryId = new Guid("e4c3b1ee-419a-41e4-a3c2-c173509a81de"),
                            Description = "500W con 3 velocità",
                            Image = "images/FrullatoreCompact.png",
                            IsBestSeller = false,
                            Name = "Frullatore Compact",
                            Price = 45.00m,
                            Producer = "Kenwood",
                            Quantity = 15
                        },
                        new
                        {
                            Id = new Guid("d85f8df7-4f2c-4fd8-b77c-c8374193f9ea"),
                            CategoryId = new Guid("e4c3b1ee-419a-41e4-a3c2-c173509a81de"),
                            Description = "Senza sacco, 2000W",
                            Image = "images/aspirapolvere.jpg",
                            IsBestSeller = true,
                            Name = "Aspirapolvere Cyclone",
                            Price = 129.90m,
                            Producer = "Hoover",
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("ac53b353-93ce-4cc1-9019-e4e46dc1e777"),
                            CategoryId = new Guid("9fdfcfb3-54f0-4707-bf4b-3cf8e87efaa9"),
                            Description = "Effetto lifting immediato",
                            Image = "images/Crema-Anti-Age.jpg",
                            IsBestSeller = false,
                            Name = "Crema Anti-Age",
                            Price = 22.99m,
                            Producer = "Vichy",
                            Quantity = 20
                        },
                        new
                        {
                            Id = new Guid("1c53e7cf-8591-406a-97e5-1a8d730d420f"),
                            CategoryId = new Guid("2ed3f445-d087-4f76-a3e7-9c278dc160c1"),
                            Description = "Contapassi, sonno e cardio",
                            Image = "images/SmartwatchFitGo.png",
                            IsBestSeller = true,
                            Name = "Smartwatch FitGo",
                            Price = 89.90m,
                            Producer = "FitTech",
                            Quantity = 40
                        },
                        new
                        {
                            Id = new Guid("af0997d3-646a-4f4f-b0d0-dbe76c67e0cf"),
                            CategoryId = new Guid("e4c3b1ee-419a-41e4-a3c2-c173509a81de"),
                            Description = "Vapore potente e continuo",
                            Image = "images/Ferro_da_stiro_SteamMax.jpg",
                            IsBestSeller = false,
                            Name = "Ferro da stiro SteamMax",
                            Price = 39.90m,
                            Producer = "Rowenta",
                            Quantity = 18
                        },
                        new
                        {
                            Id = new Guid("ff6c85bb-07c6-4081-87ab-c3856b7035e0"),
                            CategoryId = new Guid("e4c3b1ee-419a-41e4-a3c2-c173509a81de"),
                            Description = "Tecnologia ionica",
                            Image = "images/phon.jpg",
                            IsBestSeller = true,
                            Name = "Asciugacapelli ProDry",
                            Price = 34.50m,
                            Producer = "Philips",
                            Quantity = 22
                        },
                        new
                        {
                            Id = new Guid("ae3fa6a3-7c0f-4e07-9c35-2f2823a98900"),
                            CategoryId = new Guid("f83c2b7e-1d2e-4c1f-a51f-8b745f4e5b9b"),
                            Description = "Maglia 'Iron Grey' – Uomo, tessuto traspirante con stile unico",
                            Image = "images/M+J+BIKE+JERSEY.png",
                            IsBestSeller = true,
                            Name = "Jordan x Nigel Sylvester",
                            Price = 149.99m,
                            Producer = "Nike",
                            Quantity = 15
                        },
                        new
                        {
                            Id = new Guid("33a2de52-3489-4780-9fe3-61e6eec6c12e"),
                            CategoryId = new Guid("21f3cb15-5054-4a3a-8752-f26262ff0e88"),
                            Description = "Tavola gonfiabile per sport acquatici con montaggio facile",
                            Image = "images/cressiSup.jpg",
                            IsBestSeller = false,
                            Name = "Tavola SUP Cressi Solid Isup",
                            Price = 399.99m,
                            Producer = "Cressi",
                            Quantity = 7
                        },
                        new
                        {
                            Id = new Guid("0a6f1ec5-7db2-43f7-a48d-84d946e82cf1"),
                            CategoryId = new Guid("9fdfcfb3-54f0-4707-bf4b-3cf8e87efaa9"),
                            Description = "Trattamento anti-imperfezioni per pelli grasse a tendenza acneica",
                            Image = "images/LaRoche-PosayEffaclarDuo+.jpg",
                            IsBestSeller = true,
                            Name = "La Roche-Posay Effaclar Duo+",
                            Price = 16.90m,
                            Producer = "La Roche-Posay",
                            Quantity = 30
                        },
                        new
                        {
                            Id = new Guid("27429eb0-31fb-4204-8542-bc1aa8c0ac49"),
                            CategoryId = new Guid("9fdfcfb3-54f0-4707-bf4b-3cf8e87efaa9"),
                            Description = "Balsamo lenitivo multiuso per pelli sensibili, secche o irritate",
                            Image = "images/LaRoche-PosayCicaplastBaumeB5.jpg",
                            IsBestSeller = true,
                            Name = "La Roche-Posay Cicaplast Baume B5",
                            Price = 14.50m,
                            Producer = "La Roche-Posay",
                            Quantity = 30
                        },
                        new
                        {
                            Id = new Guid("502f5516-fd2e-440b-9e7b-0076079f449b"),
                            CategoryId = new Guid("9fdfcfb3-54f0-4707-bf4b-3cf8e87efaa9"),
                            Description = "Crema viso idratante con acido ialuronico per pelle fresca e morbida",
                            Image = "images/NeutrogenaHydroBoostWaterGel.jpg",
                            IsBestSeller = true,
                            Name = "Neutrogena Hydro Boost Water Gel",
                            Price = 11.90m,
                            Producer = "Neutrogena",
                            Quantity = 26
                        },
                        new
                        {
                            Id = new Guid("c6364cb7-be80-4452-938c-3ace0f7e8c56"),
                            CategoryId = new Guid("9fdfcfb3-54f0-4707-bf4b-3cf8e87efaa9"),
                            Description = "Crema giorno anti-età con olio di lavanda bio, adatta a tutti i tipi di pelle",
                            Image = "images/GarnierBioCremaAnti-Age.jpg",
                            IsBestSeller = true,
                            Name = "Garnier Bio Crema Anti-Age",
                            Price = 8.99m,
                            Producer = "Garnier",
                            Quantity = 31
                        },
                        new
                        {
                            Id = new Guid("d2261678-527e-4afb-b52b-55d0fafdc2a8"),
                            CategoryId = new Guid("9fdfcfb3-54f0-4707-bf4b-3cf8e87efaa9"),
                            Description = "Crema giorno anti-rughe con Q10 e creatina per pelli mature",
                            Image = "images/NiveaQ10PowerAnti-Rughe.jpg",
                            IsBestSeller = true,
                            Name = "Nivea Q10 Power Anti-Rughe",
                            Price = 9.90m,
                            Producer = "Nivea",
                            Quantity = 11
                        },
                        new
                        {
                            Id = new Guid("b94cb48e-104b-42c7-a218-fad725e476a2"),
                            CategoryId = new Guid("9fdfcfb3-54f0-4707-bf4b-3cf8e87efaa9"),
                            Description = "Siero viso riduttore di imperfezioni e regolatore di sebo",
                            Image = "images/TheOrdinaryNiacinamide.jpg",
                            IsBestSeller = false,
                            Name = "The Ordinary Niacinamide 10% + Zinc 1%",
                            Price = 6.80m,
                            Producer = "The Ordinary",
                            Quantity = 27
                        },
                        new
                        {
                            Id = new Guid("736a5f6f-5d2e-4b5f-b83c-5b8fde368424"),
                            CategoryId = new Guid("9fdfcfb3-54f0-4707-bf4b-3cf8e87efaa9"),
                            Description = "Siero rassodante viso effetto lifting immediato",
                            Image = "images/LieracLiftIntegral.jpg",
                            IsBestSeller = false,
                            Name = "Lierac Lift Integral Siero",
                            Price = 39.90m,
                            Producer = "Lierac",
                            Quantity = 41
                        },
                        new
                        {
                            Id = new Guid("5fc54f21-39e0-4d3d-8475-24ad4f53cf72"),
                            CategoryId = new Guid("9fdfcfb3-54f0-4707-bf4b-3cf8e87efaa9"),
                            Description = "Siero quotidiano con acido ialuronico e acqua vulcanica per rinforzare la barriera cutanea",
                            Image = "images/VichyMineral89.jpg",
                            IsBestSeller = false,
                            Name = "Vichy Mineral 89",
                            Price = 21.00m,
                            Producer = "Vichy",
                            Quantity = 11
                        },
                        new
                        {
                            Id = new Guid("e6c61ffa-0fd5-4df2-9a99-5fa0cc052853"),
                            CategoryId = new Guid("9fdfcfb3-54f0-4707-bf4b-3cf8e87efaa9"),
                            Description = "Olio dermocosmetico contro cicatrici, smagliature e pelle disidratata",
                            Image = "images/BioOilTrattamentoPelle.jpg",
                            IsBestSeller = true,
                            Name = "Bio Oil Trattamento Pelle",
                            Price = 12.99m,
                            Producer = "Bio Oil",
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("05292ae8-07ed-46aa-9f1d-9fc3351f299d"),
                            CategoryId = new Guid("9fdfcfb3-54f0-4707-bf4b-3cf8e87efaa9"),
                            Description = "Crema rimpolpante con acido ialuronico puro per pelle rimpolpata e distesa",
                            Image = "images/LOrealRevitaliftFiller.jpg",
                            IsBestSeller = true,
                            Name = "L'Oreal Revitalift Filler",
                            Price = 17.89m,
                            Producer = "L'Oreal",
                            Quantity = 29
                        },
                        new
                        {
                            Id = new Guid("54506198-9f20-4da0-ae3c-2db10b81945c"),
                            CategoryId = new Guid("2ed3f445-d087-4f76-a3e7-9c278dc160c1"),
                            Description = "Auricolari wireless con cancellazione attiva del rumore e audio spaziale",
                            Image = "images/AppleAirPodsPro.jpg",
                            IsBestSeller = true,
                            Name = "Apple AirPods Pro (2ª generazione)",
                            Price = 279.00m,
                            Producer = "Apple",
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("089b803d-c132-4c16-bb09-d30d831e6cf6"),
                            CategoryId = new Guid("2ed3f445-d087-4f76-a3e7-9c278dc160c1"),
                            Description = "Smartwatch con display Super AMOLED, tracciamento sonno e ECG",
                            Image = "images/SamsungGalaxyWatch6.jpg",
                            IsBestSeller = false,
                            Name = "Samsung Galaxy Watch 6",
                            Price = 319.99m,
                            Producer = "Samsung",
                            Quantity = 33
                        },
                        new
                        {
                            Id = new Guid("bb06d6a8-a8b1-4f21-bbe6-f8dc371a687e"),
                            CategoryId = new Guid("2ed3f445-d087-4f76-a3e7-9c278dc160c1"),
                            Description = "Lettore eBook impermeabile con luce regolabile e schermo antiriflesso da 6.8 pollici",
                            Image = "images/KindlePaperwhite.jpg",
                            IsBestSeller = false,
                            Name = "Kindle Paperwhite 11ª gen",
                            Price = 159.99m,
                            Producer = "Amazon",
                            Quantity = 16
                        },
                        new
                        {
                            Id = new Guid("80f2b221-2498-44c4-8ae5-6c8a35b80ff3"),
                            CategoryId = new Guid("2ed3f445-d087-4f76-a3e7-9c278dc160c1"),
                            Description = "Streaming in 4K HDR con telecomando e assistente vocale",
                            Image = "images/GoogleChromecast.jpg",
                            IsBestSeller = false,
                            Name = "Google Chromecast con Google TV",
                            Price = 69.99m,
                            Producer = "Google",
                            Quantity = 46
                        },
                        new
                        {
                            Id = new Guid("7b84e964-50f0-4a17-b4a2-026d7629a5c4"),
                            CategoryId = new Guid("2ed3f445-d087-4f76-a3e7-9c278dc160c1"),
                            Description = "Smartphone Android 6.6'' AMOLED 120Hz, 128GB, Fotocamera 108MP",
                            Image = "images/XiaomiRedmiNote13.jpg",
                            IsBestSeller = false,
                            Name = "Xiaomi Redmi Note 13",
                            Price = 199.90m,
                            Producer = "Xiaomi",
                            Quantity = 33
                        },
                        new
                        {
                            Id = new Guid("6cfa90ba-ba8e-4140-b4b6-0c82cc489973"),
                            CategoryId = new Guid("2ed3f445-d087-4f76-a3e7-9c278dc160c1"),
                            Description = "Smart speaker con Alexa e sensore di temperatura integrato",
                            Image = "images/EchoDot(5_generazione).jpg",
                            IsBestSeller = true,
                            Name = "Echo Dot (5ª generazione)",
                            Price = 64.99m,
                            Producer = "Amazon",
                            Quantity = 34
                        },
                        new
                        {
                            Id = new Guid("072f737f-fe24-4607-8caf-0a0ce58f3ff0"),
                            CategoryId = new Guid("2ed3f445-d087-4f76-a3e7-9c278dc160c1"),
                            Description = "SSD PCIe 4.0 M.2 ultra veloce per gaming e editing",
                            Image = "images/SamsungSSD980PRO1TBNVMe.jpg",
                            IsBestSeller = true,
                            Name = "Samsung SSD 980 PRO 1TB NVMe",
                            Price = 149.99m,
                            Producer = "Samsung",
                            Quantity = 24
                        },
                        new
                        {
                            Id = new Guid("a6756a0c-3815-4a93-a667-a369f6aeb0f5"),
                            CategoryId = new Guid("2ed3f445-d087-4f76-a3e7-9c278dc160c1"),
                            Description = "Power bank ad alta capacità con doppia porta USB e ricarica rapida",
                            Image = "images/AnkerPowerCore20000mAh.jpg",
                            IsBestSeller = false,
                            Name = "Anker PowerCore 20000 mAh",
                            Price = 49.99m,
                            Producer = "Anker",
                            Quantity = 15
                        },
                        new
                        {
                            Id = new Guid("a2f205bc-27ea-418c-ba00-5e13b2b03885"),
                            CategoryId = new Guid("2ed3f445-d087-4f76-a3e7-9c278dc160c1"),
                            Description = "Mouse wireless ergonomico con scorrimento elettromagnetico e sensore 8K DPI",
                            Image = "images/LogitechMXMaster3S.jpg",
                            IsBestSeller = false,
                            Name = "Logitech MX Master 3S",
                            Price = 119.00m,
                            Producer = "Logitech",
                            Quantity = 25
                        },
                        new
                        {
                            Id = new Guid("f73b6f10-6a71-56f5-98f3-abded94bf571"),
                            CategoryId = new Guid("e4c3b1ee-419a-41e4-a3c2-c173509a81de"),
                            Description = "Multicooker intelligente con 100 ricette integrate",
                            Image = "images/MoulinexCookeo.jpg",
                            IsBestSeller = true,
                            Name = "Moulinex Cookeo CE7041",
                            Price = 199.99m,
                            Producer = "Moulinex",
                            Quantity = 15
                        },
                        new
                        {
                            Id = new Guid("f62b5f09-5a60-45f4-97f2-abded93bf460"),
                            CategoryId = new Guid("e4c3b1ee-419a-41e4-a3c2-c173509a81de"),
                            Description = "Friggitrice ad aria da 6.2L con tecnologia Rapid Air per cucinare con poco olio",
                            Image = "images/PhilipsAirfryerXLEssential.jpg",
                            IsBestSeller = false,
                            Name = "Philips Airfryer XL Essential",
                            Price = 129.99m,
                            Producer = "Philips",
                            Quantity = 18
                        },
                        new
                        {
                            Id = new Guid("fd8ca21e-ad1b-458f-a8ad-ff3366acdea9"),
                            CategoryId = new Guid("e4c3b1ee-419a-41e4-a3c2-c173509a81de"),
                            Description = "Macchina automatica per caffè in chicchi con pannarello e display soft touch",
                            Image = "images/DeLonghiMagnificaStart.jpg",
                            IsBestSeller = true,
                            Name = "De'Longhi Magnifica Start",
                            Price = 319.99m,
                            Producer = "De'Longhi",
                            Quantity = 21
                        },
                        new
                        {
                            Id = new Guid("b9e38a4d-0d97-4652-b8d1-ea306ac0627e"),
                            CategoryId = new Guid("e4c3b1ee-419a-41e4-a3c2-c173509a81de"),
                            Description = "Coperta riscaldante matrimoniale con controllo temperatura e spegnimento automatico",
                            Image = "images/ImetecScaldasonno.jpg",
                            IsBestSeller = true,
                            Name = "Imetec Scaldasonno Sensitive",
                            Price = 79.90m,
                            Producer = "Imetec",
                            Quantity = 30
                        },
                        new
                        {
                            Id = new Guid("863b15aa-e0ab-4e4d-9349-e3cb085fb6a6"),
                            CategoryId = new Guid("e4c3b1ee-419a-41e4-a3c2-c173509a81de"),
                            Description = "Lavastoviglie da incasso 60 cm con 5 programmi e funzione ExtraDry",
                            Image = "images/BoschSerie2Lavastoviglie.jpg",
                            IsBestSeller = false,
                            Name = "Bosch Serie 2 Lavastoviglie",
                            Price = 399.99m,
                            Producer = "Bosch",
                            Quantity = 31
                        },
                        new
                        {
                            Id = new Guid("99f109ae-3033-4a83-9aef-8c1c1ce08b80"),
                            CategoryId = new Guid("e4c3b1ee-419a-41e4-a3c2-c173509a81de"),
                            Description = "Aspirapolvere con sacco, 4.5L, alta potenza e filtraggio avanzato",
                            Image = "images/RowentaCompactPowerXXL.jpg",
                            IsBestSeller = false,
                            Name = "Rowenta Compact Power XXL",
                            Price = 109.00m,
                            Producer = "Rowenta",
                            Quantity = 20
                        },
                        new
                        {
                            Id = new Guid("359bc919-86e3-431b-8b72-5b83018de709"),
                            CategoryId = new Guid("e4c3b1ee-419a-41e4-a3c2-c173509a81de"),
                            Description = "Robot multifunzione da 700W con accessori inclusi per impastare, tritare e grattugiare",
                            Image = "images/MoulinexEasyForceRobotdaCucina.jpg",
                            IsBestSeller = true,
                            Name = "Moulinex Easy Force Robot da Cucina",
                            Price = 89.99m,
                            Producer = "Moulinex",
                            Quantity = 50
                        },
                        new
                        {
                            Id = new Guid("76b79275-5642-4c40-9cd6-9360a1f16f11"),
                            CategoryId = new Guid("e4c3b1ee-419a-41e4-a3c2-c173509a81de"),
                            Description = "Scopa elettrica senza fili con autonomia fino a 40 minuti",
                            Image = "images/HooverHFree100.jpg",
                            IsBestSeller = false,
                            Name = "Hoover H-Free 100",
                            Price = 159.99m,
                            Producer = "Hoover",
                            Quantity = 15
                        },
                        new
                        {
                            Id = new Guid("b99f74d1-bb8a-4c0d-bcdf-bfb5060de4e1"),
                            CategoryId = new Guid("e4c3b1ee-419a-41e4-a3c2-c173509a81de"),
                            Description = "Forno elettrico da incasso 71L, classe A, con funzione grill e display LED",
                            Image = "images/BekoFornoVentilato.jpg",
                            IsBestSeller = false,
                            Name = "Beko Forno Ventilato BIE22300",
                            Price = 299.99m,
                            Producer = "Beko",
                            Quantity = 34
                        },
                        new
                        {
                            Id = new Guid("7c1a6983-a0f4-4971-bde8-ca1f5f4954ba"),
                            CategoryId = new Guid("e4c3b1ee-419a-41e4-a3c2-c173509a81de"),
                            Description = "Lavatrice 8kg, 1200 giri, tecnologia SensiCare per un bucato delicato",
                            Image = "images/ElectroluxPerfectCare600.jpg",
                            IsBestSeller = true,
                            Name = "Electrolux PerfectCare 600",
                            Price = 469.00m,
                            Producer = "Electrolux",
                            Quantity = 30
                        },
                        new
                        {
                            Id = new Guid("3a8c19f4-fda5-5f4e-a861-a2455dc4dd90"),
                            CategoryId = new Guid("f83c2b7e-1d2e-4c1f-a51f-8b745f4e5b9b"),
                            Description = "Jeans classico taglio dritto, denim blu",
                            Image = "images/Levis501OriginalJeansDonna.jpg",
                            IsBestSeller = true,
                            Name = "Levi's 501 Original Jeans",
                            Price = 89.00m,
                            Producer = "Levi's",
                            Quantity = 35
                        },
                        new
                        {
                            Id = new Guid("2a7c08f3-fda4-4f3e-a750-a1344dc3dd89"),
                            CategoryId = new Guid("f83c2b7e-1d2e-4c1f-a51f-8b745f4e5b9b"),
                            Description = "T-shirt sportiva traspirante con tecnologia Dri-FIT",
                            Image = "images/NikeDri-FITAcademyT-ShirtUomo.jpg",
                            IsBestSeller = true,
                            Name = "Nike Dri-FIT Academy T-Shirt Uomo",
                            Price = 27.99m,
                            Producer = "Nike",
                            Quantity = 22
                        },
                        new
                        {
                            Id = new Guid("2d47f5dc-2bac-4ee7-b80b-a402ec6400c8"),
                            CategoryId = new Guid("f83c2b7e-1d2e-4c1f-a51f-8b745f4e5b9b"),
                            Description = "Felpa con cappuccio in cotone misto, stile casual",
                            Image = "images/AdidasEssentials.jpg",
                            IsBestSeller = true,
                            Name = "Adidas Essentials Felpa Con Cappuccio",
                            Price = 54.99m,
                            Producer = "Adidas",
                            Quantity = 41
                        },
                        new
                        {
                            Id = new Guid("68f65a13-8fbc-4153-9283-e2126bb891be"),
                            CategoryId = new Guid("f83c2b7e-1d2e-4c1f-a51f-8b745f4e5b9b"),
                            Description = "Jeans classici regular fit in denim di alta qualità",
                            Image = "images/Levis501OriginalJeans.jpg",
                            IsBestSeller = true,
                            Name = "Levi's 501 Original Jeans Uomo",
                            Price = 89.90m,
                            Producer = "Levi's",
                            Quantity = 28
                        },
                        new
                        {
                            Id = new Guid("a8efdc2c-d690-418c-8d8f-3f305edd3dba"),
                            CategoryId = new Guid("f83c2b7e-1d2e-4c1f-a51f-8b745f4e5b9b"),
                            Description = "T-shirt con logo stampato, in cotone sostenibile",
                            Image = "images/PumaT-ShirtDonna.jpg",
                            IsBestSeller = true,
                            Name = "Puma Essentials Logo T-Shirt Donna",
                            Price = 16.99m,
                            Producer = "Puma",
                            Quantity = 48
                        },
                        new
                        {
                            Id = new Guid("7b45e7fa-d812-4d20-9579-324ec3ff92cd"),
                            CategoryId = new Guid("f83c2b7e-1d2e-4c1f-a51f-8b745f4e5b9b"),
                            Description = "Set di slip in cotone elasticizzato con logo in vita",
                            Image = "images/CalvinKleinSlipUomo(3Pezzi).jpg",
                            IsBestSeller = true,
                            Name = "Calvin Klein Slip Uomo (3 Pezzi)",
                            Price = 39.90m,
                            Producer = "Calvin Klein",
                            Quantity = 30
                        },
                        new
                        {
                            Id = new Guid("14d62de2-fa36-46d2-8b42-3422bfe3e058"),
                            CategoryId = new Guid("f83c2b7e-1d2e-4c1f-a51f-8b745f4e5b9b"),
                            Description = "Giacca leggera e impermeabile con cuciture termosaldate",
                            Image = "images/NorthFaceGiaccaVenture2.jpg",
                            IsBestSeller = true,
                            Name = "North Face Giacca Antipioggia Venture 2",
                            Price = 129.00m,
                            Producer = "The North Face",
                            Quantity = 20
                        },
                        new
                        {
                            Id = new Guid("f8e191d5-b382-4508-b4f9-70f97b7df8eb"),
                            CategoryId = new Guid("f83c2b7e-1d2e-4c1f-a51f-8b745f4e5b9b"),
                            Description = "Infradito estive classiche, comode e colorate",
                            Image = "images/HavaianasBrasilLogoInfradito.jpg",
                            IsBestSeller = true,
                            Name = "Havaianas Brasil Logo Infradito",
                            Price = 21.99m,
                            Producer = "Havaianas",
                            Quantity = 50
                        },
                        new
                        {
                            Id = new Guid("1f33cfa7-f52f-4076-8930-0f848b44cc34"),
                            CategoryId = new Guid("f83c2b7e-1d2e-4c1f-a51f-8b745f4e5b9b"),
                            Description = "Polo elegante in piqué con logo ricamato",
                            Image = "images/TommyHilfigerPoloBasic.jpg",
                            IsBestSeller = false,
                            Name = "Tommy Hilfiger Polo Basic",
                            Price = 44.90m,
                            Producer = "Tommy Hilfiger",
                            Quantity = 23
                        },
                        new
                        {
                            Id = new Guid("8e68cb91-265e-4f9f-bc37-a7580e905e87"),
                            CategoryId = new Guid("f83c2b7e-1d2e-4c1f-a51f-8b745f4e5b9b"),
                            Description = "Felpa in cotone pesante con logo sul petto",
                            Image = "images/ChampionFelpa.jpg",
                            IsBestSeller = true,
                            Name = "Champion Felpa Girocollo Small Logo",
                            Price = 39.90m,
                            Producer = "Champion",
                            Quantity = 16
                        },
                        new
                        {
                            Id = new Guid("f171c52e-5b38-41a9-b05b-d8087b4d306f"),
                            CategoryId = new Guid("21f3cb15-5054-4a3a-8752-f26262ff0e88"),
                            Description = "Modello da costruire del famoso X-Wing Starfighter",
                            Image = "images/LEGOStarWarsX-Wing.jpg",
                            IsBestSeller = true,
                            Name = "LEGO Star Wars X-Wing",
                            Price = 54.99m,
                            Producer = "LEGO",
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("bb102144-a85e-4561-a18d-bbcb1060d2e1"),
                            CategoryId = new Guid("21f3cb15-5054-4a3a-8752-f26262ff0e88"),
                            Description = "Modellino da Costruire di Astronave da Collezione con Supporto, Idea Regalo di Compleanno per Adulti, Uomo, Donna e Fan dell'Attacco dei Cloni",
                            Image = "images/LEGOStarWars75404.jpg",
                            IsBestSeller = false,
                            Name = "lego star wars x-wing fighter di luke skywalker 75301",
                            Price = 164.05m,
                            Producer = "LEGO",
                            Quantity = 27
                        },
                        new
                        {
                            Id = new Guid("a6c6f8da-1f4d-42b5-b1ae-15dc5f1a2301"),
                            CategoryId = new Guid("21f3cb15-5054-4a3a-8752-f26262ff0e88"),
                            Description = "Set 3-in-1 per costruire robot, drago o jet",
                            Image = "images/LEGOCreator3-in-1.jpg",
                            IsBestSeller = true,
                            Name = "LEGO Creator 3-in-1 Super Robot",
                            Price = 19.99m,
                            Producer = "LEGO",
                            Quantity = 20
                        },
                        new
                        {
                            Id = new Guid("493334d1-8d12-494b-8485-ef912c907dc7"),
                            CategoryId = new Guid("21f3cb15-5054-4a3a-8752-f26262ff0e88"),
                            Description = "Gioco da tavolo di compravendita di proprietà",
                            Image = "images/MonopolyClassicoHasbro.jpg",
                            IsBestSeller = true,
                            Name = "Monopoly Classico Hasbro",
                            Price = 29.90m,
                            Producer = "Hasbro",
                            Quantity = 35
                        },
                        new
                        {
                            Id = new Guid("4cc1a3cb-fde8-465a-a44f-86fef040cba4"),
                            CategoryId = new Guid("21f3cb15-5054-4a3a-8752-f26262ff0e88"),
                            Description = "Puzzle 2000 pezzi, qualità premium",
                            Image = "images/puzzle.jpg",
                            IsBestSeller = false,
                            Name = "Puzzle Ravensburger 2000 Pezzi",
                            Price = 16.95m,
                            Producer = "Ravensburger",
                            Quantity = 18
                        },
                        new
                        {
                            Id = new Guid("01139b0c-abe7-4775-886c-753303db2a0e"),
                            CategoryId = new Guid("21f3cb15-5054-4a3a-8752-f26262ff0e88"),
                            Description = "Gioco di carte UNO classico per tutta la famiglia",
                            Image = "images/CarteUNOMattel.jpg",
                            IsBestSeller = true,
                            Name = "Set di Carte UNO Mattel",
                            Price = 8.99m,
                            Producer = "Mattel",
                            Quantity = 50
                        },
                        new
                        {
                            Id = new Guid("f9ed47a1-d949-482e-83f0-c3b80c1e6f19"),
                            CategoryId = new Guid("21f3cb15-5054-4a3a-8752-f26262ff0e88"),
                            Description = "Gioco di abilità giapponese in legno colorato",
                            Image = "images/KendamaKromPop.jpg",
                            IsBestSeller = false,
                            Name = "Kendama Krom Pop",
                            Price = 24.90m,
                            Producer = "KROM",
                            Quantity = 15
                        },
                        new
                        {
                            Id = new Guid("c6103378-7a02-449d-a53e-9fdf1d8d3ef9"),
                            CategoryId = new Guid("21f3cb15-5054-4a3a-8752-f26262ff0e88"),
                            Description = "Frisbee per sport all'aperto, lunga gittata",
                            Image = "images/FrisbeeAerobiePro.jpg",
                            IsBestSeller = true,
                            Name = "Set 3 Frisbee Aerobie Pro",
                            Price = 17.50m,
                            Producer = "Aerobie",
                            Quantity = 28
                        },
                        new
                        {
                            Id = new Guid("e2794eca-7808-402c-83de-97a3b2e9d930"),
                            CategoryId = new Guid("21f3cb15-5054-4a3a-8752-f26262ff0e88"),
                            Description = "Pallone resistente ideale per il tempo libero",
                            Image = "images/PalloneAdidasTango.jpg",
                            IsBestSeller = true,
                            Name = "Pallone da Calcio Adidas Tango",
                            Price = 14.99m,
                            Producer = "Adidas",
                            Quantity = 32
                        },
                        new
                        {
                            Id = new Guid("8e8b5685-1366-4e53-b99c-016f75bfaa09"),
                            CategoryId = new Guid("21f3cb15-5054-4a3a-8752-f26262ff0e88"),
                            Description = "Diabolo per giocoleria con bastoncini in legno",
                            Image = "images/DiaboloJuggleDreamBastoncini.jpg",
                            IsBestSeller = false,
                            Name = "Diabolo Juggle Dream con Bastoncini",
                            Price = 19.95m,
                            Producer = "Juggle Dream",
                            Quantity = 40
                        },
                        new
                        {
                            Id = new Guid("8b0b2745-b584-4ec5-b293-91e692a48166"),
                            CategoryId = new Guid("21f3cb15-5054-4a3a-8752-f26262ff0e88"),
                            Description = "Set completo con racchette, palline e rete da tavolo",
                            Image = "images/SetPingPongPortatileJOOLA.jpg",
                            IsBestSeller = true,
                            Name = "Set Ping Pong Portatile JOOLA",
                            Price = 24.99m,
                            Producer = "JOOLA",
                            Quantity = 19
                        },
                        new
                        {
                            Id = new Guid("0342134e-4a4d-4a26-8d3f-9955a2aa7d82"),
                            CategoryId = new Guid("adbf2d17-62c6-44a7-a6d7-d09d510674c5"),
                            Description = "Set di manubri regolabili da 2 a 24 kg",
                            Image = "images/ManubriRegolabiliBowflexSelectTech552.jpg",
                            IsBestSeller = true,
                            Name = "Manubri Regolabili Bowflex SelectTech 552",
                            Price = 399.00m,
                            Producer = "Bowflex",
                            Quantity = 15
                        },
                        new
                        {
                            Id = new Guid("05c44beb-5677-4cc8-93b5-a66197c1b2de"),
                            CategoryId = new Guid("adbf2d17-62c6-44a7-a6d7-d09d510674c5"),
                            Description = "Tappetino professionale antiscivolo per yoga",
                            Image = "images/TappetinoYogaMandukaPRO.jpg",
                            IsBestSeller = true,
                            Name = "Tappetino Yoga Manduka PRO",
                            Price = 119.00m,
                            Producer = "Manduka",
                            Quantity = 40
                        },
                        new
                        {
                            Id = new Guid("ffed2955-d6c1-4951-878f-a59ef6f96c2a"),
                            CategoryId = new Guid("adbf2d17-62c6-44a7-a6d7-d09d510674c5"),
                            Description = "Palla da ginnastica 65cm con pompa inclusa",
                            Image = "images/PalladaPilatesGaiam.jpg",
                            IsBestSeller = false,
                            Name = "Palla da Pilates Gaiam",
                            Price = 21.99m,
                            Producer = "Gaiam",
                            Quantity = 30
                        },
                        new
                        {
                            Id = new Guid("2f24edd3-3568-4d52-8757-4cbdcf432614"),
                            CategoryId = new Guid("adbf2d17-62c6-44a7-a6d7-d09d510674c5"),
                            Description = "Corda per salti rapidi regolabile in lunghezza",
                            Image = "images/CordaXSaltareBeMaxx.jpg",
                            IsBestSeller = true,
                            Name = "Corda per Saltare Speed Rope BeMaxx",
                            Price = 16.90m,
                            Producer = "BeMaxx",
                            Quantity = 50
                        },
                        new
                        {
                            Id = new Guid("3a44b124-e862-4080-bb84-de6a9b1c423e"),
                            CategoryId = new Guid("adbf2d17-62c6-44a7-a6d7-d09d510674c5"),
                            Description = "Rullo foam per massaggi e rilascio miofasciale",
                            Image = "images/RulloMassaggianteGRID.jpg",
                            IsBestSeller = false,
                            Name = "Rullo Massaggiante TriggerPoint GRID",
                            Price = 38.90m,
                            Producer = "TriggerPoint",
                            Quantity = 25
                        },
                        new
                        {
                            Id = new Guid("6c91be01-d178-4dc7-bfc3-26dc8bedca3b"),
                            CategoryId = new Guid("adbf2d17-62c6-44a7-a6d7-d09d510674c5"),
                            Description = "Kit completo per allenamento in sospensione",
                            Image = "images/TRXSuspensionTrainingKit.jpg",
                            IsBestSeller = true,
                            Name = "TRX Suspension Training Kit",
                            Price = 139.00m,
                            Producer = "TRX",
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("5cd30429-e765-4685-b327-ec48434bdc87"),
                            CategoryId = new Guid("adbf2d17-62c6-44a7-a6d7-d09d510674c5"),
                            Description = "Kettlebell classico per cross training e forza",
                            Image = "images/Kettlebell12kg.jpg",
                            IsBestSeller = true,
                            Name = "Kettlebell in Ghisa PROIRON 12kg",
                            Price = 39.90m,
                            Producer = "PROIRON",
                            Quantity = 18
                        },
                        new
                        {
                            Id = new Guid("057beaa9-5f4c-43e3-8b5d-d5eca661439b"),
                            CategoryId = new Guid("adbf2d17-62c6-44a7-a6d7-d09d510674c5"),
                            Description = "Panca da allenamento stabile e robusta",
                            Image = "images/PancaPianaPerformance.jpg",
                            IsBestSeller = false,
                            Name = "Panca Piana Adidas Performance",
                            Price = 99.99m,
                            Producer = "Adidas",
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("5171273c-570d-4642-b5a3-81e0050e0331"),
                            CategoryId = new Guid("adbf2d17-62c6-44a7-a6d7-d09d510674c5"),
                            Description = "5 fasce elastiche con maniglie e accessori",
                            Image = "images/SetElastici.jpg",
                            IsBestSeller = true,
                            Name = "Set Elastici di Resistenza FitBeast",
                            Price = 29.99m,
                            Producer = "FitBeast",
                            Quantity = 35
                        },
                        new
                        {
                            Id = new Guid("64462dc7-2faa-4f1c-9769-2a283deafca7"),
                            CategoryId = new Guid("ab73a4ea-76fd-41cb-8a4d-4b0e9b610e38"),
                            Description = "Crocchette per cani adulti di taglia grande",
                            Image = "images/RoyalCanin15kg.jpg",
                            IsBestSeller = true,
                            Name = "Royal Canin Maxi Adult 15kg",
                            Price = 64.99m,
                            Producer = "Royal Canin",
                            Quantity = 20
                        },
                        new
                        {
                            Id = new Guid("1ae30f94-92bc-4316-9346-58a612ae32f0"),
                            CategoryId = new Guid("ab73a4ea-76fd-41cb-8a4d-4b0e9b610e38"),
                            Description = "Alimento completo per gatti sterilizzati",
                            Image = "images/Purina3kg.jpg",
                            IsBestSeller = true,
                            Name = "Purina One Sterilcat 3kg",
                            Price = 16.99m,
                            Producer = "Purina",
                            Quantity = 35
                        },
                        new
                        {
                            Id = new Guid("ce7b2cbd-2b63-4381-8ef2-4b75bca3a02c"),
                            CategoryId = new Guid("ab73a4ea-76fd-41cb-8a4d-4b0e9b610e38"),
                            Description = "Tiragraffi a torre con cuccia e piattaforme",
                            Image = "images/TiragraffiGatti.jpg",
                            IsBestSeller = false,
                            Name = "Tiragraffi Relax per Gatti",
                            Price = 44.90m,
                            Producer = "FEANDREA",
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("ad74ed2d-5c36-4138-9ffb-dd393587cb6b"),
                            CategoryId = new Guid("ab73a4ea-76fd-41cb-8a4d-4b0e9b610e38"),
                            Description = "Cuccia soffice per cani e gatti, lavabile",
                            Image = "images/CucciaMorbidaAmazon.jpg",
                            IsBestSeller = false,
                            Name = "Cuccia Morbida Amazon Basics",
                            Price = 24.99m,
                            Producer = "Amazon Basics",
                            Quantity = 28
                        },
                        new
                        {
                            Id = new Guid("1a343040-4549-452d-a714-b6a0ef576c16"),
                            CategoryId = new Guid("ab73a4ea-76fd-41cb-8a4d-4b0e9b610e38"),
                            Description = "Dispenser automatico smart per cani e gatti",
                            Image = "images/DispenserCiboPetkit.jpg",
                            IsBestSeller = true,
                            Name = "Dispenser Automatico Cibo Petkit",
                            Price = 89.90m,
                            Producer = "Petkit",
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("210f8b92-08ee-41cc-ae74-98c60f21849f"),
                            CategoryId = new Guid("ab73a4ea-76fd-41cb-8a4d-4b0e9b610e38"),
                            Description = "Spazzola con setole retraibili per la toelettatura",
                            Image = "images/SpazzolaAnimali.jpg",
                            IsBestSeller = true,
                            Name = "Spazzola Autopulente per Animali",
                            Price = 14.50m,
                            Producer = "Pecute",
                            Quantity = 50
                        },
                        new
                        {
                            Id = new Guid("c6ea7f07-49ec-4970-924f-907b306370c7"),
                            CategoryId = new Guid("ab73a4ea-76fd-41cb-8a4d-4b0e9b610e38"),
                            Description = "Gioco in gomma per cani da riempire con snack",
                            Image = "images/GiocoKongClassic.jpg",
                            IsBestSeller = true,
                            Name = "Gioco Interattivo Kong Classic",
                            Price = 9.99m,
                            Producer = "Kong",
                            Quantity = 60
                        },
                        new
                        {
                            Id = new Guid("d7f9d020-e965-4461-8894-a7b8ec7a7af5"),
                            CategoryId = new Guid("ab73a4ea-76fd-41cb-8a4d-4b0e9b610e38"),
                            Description = "Borsa per il trasporto di animali di piccola taglia",
                            Image = "images/trasportinoTrixie.jpg",
                            IsBestSeller = false,
                            Name = "Trasportino Morbido Trixie",
                            Price = 32.99m,
                            Producer = "Trixie",
                            Quantity = 18
                        },
                        new
                        {
                            Id = new Guid("d1e09e9a-1cca-4ba8-b93d-8d49d34583ad"),
                            CategoryId = new Guid("ab73a4ea-76fd-41cb-8a4d-4b0e9b610e38"),
                            Description = "Fontanella a fiore per gatti, stimola l’idratazione",
                            Image = "images/FontanellaAcquaFlower.jpg",
                            IsBestSeller = true,
                            Name = "Fontanella Acqua Catit Flower",
                            Price = 27.50m,
                            Producer = "Catit",
                            Quantity = 25
                        },
                        new
                        {
                            Id = new Guid("25c84f27-dab1-4dc1-a5eb-77335f0e3fdf"),
                            CategoryId = new Guid("9fdfcfb3-54f0-4707-bf4b-3cf8e87efaa9"),
                            Description = "Detergente schiumogeno per tutti i tipi di pelle.",
                            Image = "images/bionike.jpg",
                            IsBestSeller = false,
                            Name = "Detergente Viso Delicato",
                            Price = 7.99m,
                            Producer = "Bionike",
                            Quantity = 20
                        },
                        new
                        {
                            Id = new Guid("b2a7ae52-915f-4563-9d4f-accf256968f0"),
                            CategoryId = new Guid("9fdfcfb3-54f0-4707-bf4b-3cf8e87efaa9"),
                            Description = "Struccante bifasico per occhi sensibili.",
                            Image = "images/garnierStruc.jpg",
                            IsBestSeller = false,
                            Name = "Struccante Occhi",
                            Price = 5.99m,
                            Producer = "Garnier",
                            Quantity = 15
                        },
                        new
                        {
                            Id = new Guid("6a17b20e-2e8e-4b64-925c-43abfc5d24c0"),
                            CategoryId = new Guid("9fdfcfb3-54f0-4707-bf4b-3cf8e87efaa9"),
                            Description = "Siero illuminante anti-macchia.",
                            Image = "images/vitaminac.jpg",
                            IsBestSeller = false,
                            Name = "Siero Viso Vitamina C",
                            Price = 19.50m,
                            Producer = "Collistar",
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("36dbf436-d4ec-47ab-bea2-3b0df6d90dc2"),
                            CategoryId = new Guid("9fdfcfb3-54f0-4707-bf4b-3cf8e87efaa9"),
                            Description = "Maschera notte super idratante.",
                            Image = "images/maskcream.jpg",
                            IsBestSeller = false,
                            Name = "Maschera Idratante Notte",
                            Price = 13.90m,
                            Producer = "Sephora",
                            Quantity = 18
                        },
                        new
                        {
                            Id = new Guid("2e6b9b13-d9a1-4116-9c48-81ebf87e6f3e"),
                            CategoryId = new Guid("9fdfcfb3-54f0-4707-bf4b-3cf8e87efaa9"),
                            Description = "Protegge le labbra dal freddo.",
                            Image = "images/lipgloss.jpg",
                            IsBestSeller = false,
                            Name = "Burro Cacao Nutriente",
                            Price = 3.99m,
                            Producer = "Lycia",
                            Quantity = 30
                        },
                        new
                        {
                            Id = new Guid("8162ea1f-760c-40eb-9acd-8699ae5154a9"),
                            CategoryId = new Guid("2ed3f445-d087-4f76-a3e7-9c278dc160c1"),
                            Description = "Mouse wireless per lavoro e gaming.",
                            Image = "images/mousetrust.jpg",
                            IsBestSeller = false,
                            Name = "Mouse Wireless Ergonomico",
                            Price = 29.90m,
                            Producer = "Trust",
                            Quantity = 25
                        },
                        new
                        {
                            Id = new Guid("1b4962eb-a1c7-430a-84b0-3c2a48f8519f"),
                            CategoryId = new Guid("2ed3f445-d087-4f76-a3e7-9c278dc160c1"),
                            Description = "Lampadina led gestibile da smartphone.",
                            Image = "images/lampadina.jpg",
                            IsBestSeller = false,
                            Name = "Lampadina Smart WiFi",
                            Price = 14.99m,
                            Producer = "TP-Link",
                            Quantity = 60
                        },
                        new
                        {
                            Id = new Guid("ceef3dd1-7296-4b63-835a-7f7293da75a1"),
                            CategoryId = new Guid("2ed3f445-d087-4f76-a3e7-9c278dc160c1"),
                            Description = "Webcam USB con microfono integrato.",
                            Image = "images/icam.jpg",
                            IsBestSeller = false,
                            Name = "Webcam HD 1080p",
                            Price = 49.99m,
                            Producer = "Logitech",
                            Quantity = 40
                        },
                        new
                        {
                            Id = new Guid("fd431bda-ed44-4dba-bd2d-dc2ac79326b8"),
                            CategoryId = new Guid("2ed3f445-d087-4f76-a3e7-9c278dc160c1"),
                            Description = "Batteria portatile ricarica rapida.",
                            Image = "images/powerbank2.jpg",
                            IsBestSeller = false,
                            Name = "Power Bank 10000mAh",
                            Price = 21.50m,
                            Producer = "Anker",
                            Quantity = 32
                        },
                        new
                        {
                            Id = new Guid("602e1072-56f6-43b8-b349-460513fc01ab"),
                            CategoryId = new Guid("2ed3f445-d087-4f76-a3e7-9c278dc160c1"),
                            Description = "Mini speaker per ascolto musicale ovunque.",
                            Image = "images/cassaJbl.jpg",
                            IsBestSeller = false,
                            Name = "Speaker Bluetooth Portatile",
                            Price = 18.99m,
                            Producer = "JBL",
                            Quantity = 45
                        },
                        new
                        {
                            Id = new Guid("f4b15084-8dbb-47b6-8614-a83f390aa9b6"),
                            CategoryId = new Guid("e4c3b1ee-419a-41e4-a3c2-c173509a81de"),
                            Description = "Tostapane compatto con espulsione automatica.",
                            Image = "images/tostapane.jpg",
                            IsBestSeller = false,
                            Name = "Tostapane 2 Fette",
                            Price = 24.90m,
                            Producer = "Imetec",
                            Quantity = 20
                        },
                        new
                        {
                            Id = new Guid("4e145c19-e470-40d5-bd5a-5b08ae8146c4"),
                            CategoryId = new Guid("e4c3b1ee-419a-41e4-a3c2-c173509a81de"),
                            Description = "Macchina manuale per caffè macinato.",
                            Image = "images/deLonghi.jpg",
                            IsBestSeller = false,
                            Name = "Macchina Caffè Espresso",
                            Price = 69.00m,
                            Producer = "De'Longhi",
                            Quantity = 17
                        },
                        new
                        {
                            Id = new Guid("b045a87c-4b52-49d2-b5b1-81a53c6dae4b"),
                            CategoryId = new Guid("e4c3b1ee-419a-41e4-a3c2-c173509a81de"),
                            Description = "Aspirabriciole portatile senza filo.",
                            Image = "images/aspirabriciole.jpg",
                            IsBestSeller = false,
                            Name = "Aspirabriciole Ricaricabile",
                            Price = 35.00m,
                            Producer = "Rowenta",
                            Quantity = 28
                        },
                        new
                        {
                            Id = new Guid("7cafab9b-e7c5-4659-bfdc-b0d60ed9189c"),
                            CategoryId = new Guid("e4c3b1ee-419a-41e4-a3c2-c173509a81de"),
                            Description = "Microonde digitale con funzione grill.",
                            Image = "images/microonde.jpg",
                            IsBestSeller = false,
                            Name = "Forno a Microonde 20L",
                            Price = 79.90m,
                            Producer = "Samsung",
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("ec5941df-48f2-45f5-800b-8dda367e224b"),
                            CategoryId = new Guid("e4c3b1ee-419a-41e4-a3c2-c173509a81de"),
                            Description = "Ventilatore silenzioso regolabile in altezza.",
                            Image = "images/ventilatore.jpg",
                            IsBestSeller = false,
                            Name = "Ventilatore a Piantana",
                            Price = 36.90m,
                            Producer = "Ardes",
                            Quantity = 22
                        },
                        new
                        {
                            Id = new Guid("c3ed6e3c-f498-4d8e-aad0-48731b9a9fbb"),
                            CategoryId = new Guid("f83c2b7e-1d2e-4c1f-a51f-8b745f4e5b9b"),
                            Description = "Maglietta cotone uomo/donna.",
                            Image = "images/fruitoftheloom.jpg",
                            IsBestSeller = false,
                            Name = "T-Shirt Basic Bianca",
                            Price = 9.99m,
                            Producer = "Fruit of the Loom",
                            Quantity = 44
                        },
                        new
                        {
                            Id = new Guid("6096d5dc-a3f9-41d5-b8dc-2edbfb3a75e6"),
                            CategoryId = new Guid("f83c2b7e-1d2e-4c1f-a51f-8b745f4e5b9b"),
                            Description = "Shorts traspiranti per allenamento.",
                            Image = "images/pantaloncini.jpg",
                            IsBestSeller = false,
                            Name = "Pantaloncini Sportivi",
                            Price = 14.99m,
                            Producer = "Adidas",
                            Quantity = 35
                        },
                        new
                        {
                            Id = new Guid("d72e67a8-3ad0-42d6-a509-a7d5fd1176e7"),
                            CategoryId = new Guid("f83c2b7e-1d2e-4c1f-a51f-8b745f4e5b9b"),
                            Description = "Cappellino regolabile, vari colori.",
                            Image = "images/cappellinoNike.jpg",
                            IsBestSeller = false,
                            Name = "Cappellino con Visiera",
                            Price = 8.50m,
                            Producer = "Nike",
                            Quantity = 25
                        },
                        new
                        {
                            Id = new Guid("73faa235-715f-4f09-86e9-388db8689da2"),
                            CategoryId = new Guid("f83c2b7e-1d2e-4c1f-a51f-8b745f4e5b9b"),
                            Description = "Sciarpa in lana calda.",
                            Image = "images/Sciarpa.jpg",
                            IsBestSeller = false,
                            Name = "Sciarpa Lana Unisex",
                            Price = 19.90m,
                            Producer = "Benetton",
                            Quantity = 15
                        },
                        new
                        {
                            Id = new Guid("7b14cdea-69e1-4c72-b2ef-ee0dd95e091f"),
                            CategoryId = new Guid("f83c2b7e-1d2e-4c1f-a51f-8b745f4e5b9b"),
                            Description = "Scarpe basse blu stile casual.",
                            Image = "images/converse.jpg",
                            IsBestSeller = false,
                            Name = "Sneakers Casual Blu",
                            Price = 45.90m,
                            Producer = "Converse",
                            Quantity = 19
                        },
                        new
                        {
                            Id = new Guid("f3f25433-cb03-493c-a773-25aef3a80bd0"),
                            CategoryId = new Guid("21f3cb15-5054-4a3a-8752-f26262ff0e88"),
                            Description = "Set 2 racchette, 3 palline e rete.",
                            Image = "images/pingpong.jpg",
                            IsBestSeller = false,
                            Name = "Set Tennis da Tavolo",
                            Price = 22.50m,
                            Producer = "JOOLA",
                            Quantity = 18
                        },
                        new
                        {
                            Id = new Guid("0d3799fc-7168-4f17-a35b-39eda9459eae"),
                            CategoryId = new Guid("21f3cb15-5054-4a3a-8752-f26262ff0e88"),
                            Description = "Set 12 colori acrilici per hobby creativi.",
                            Image = "images/kitPittura.jpg",
                            IsBestSeller = false,
                            Name = "Kit Pittura Acrilica",
                            Price = 17.90m,
                            Producer = "Giotto",
                            Quantity = 12
                        },
                        new
                        {
                            Id = new Guid("7dad40f9-dcec-436f-a854-029ee217d500"),
                            CategoryId = new Guid("21f3cb15-5054-4a3a-8752-f26262ff0e88"),
                            Description = "Puzzle paesaggio di Venezia.",
                            Image = "images/Puzzle–Venezia.jpg",
                            IsBestSeller = false,
                            Name = "Puzzle 2000 Pezzi",
                            Price = 15.99m,
                            Producer = "Clementoni",
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("ed95dc2e-8168-44ec-ae9b-c6ad3dfcb1b2"),
                            CategoryId = new Guid("21f3cb15-5054-4a3a-8752-f26262ff0e88"),
                            Description = "Carte da gioco classiche italiane.",
                            Image = "images/CarteGioco.jpg",
                            IsBestSeller = false,
                            Name = "Gioco di Carte Scopa",
                            Price = 4.99m,
                            Producer = "Dal Negro",
                            Quantity = 26
                        },
                        new
                        {
                            Id = new Guid("4971cff6-b843-4af1-a69b-714823a5155e"),
                            CategoryId = new Guid("21f3cb15-5054-4a3a-8752-f26262ff0e88"),
                            Description = "Monopattino pieghevole per bambini 5+.",
                            Image = "images/monopattino.jpg",
                            IsBestSeller = false,
                            Name = "Monopattino per Bambini",
                            Price = 29.99m,
                            Producer = "Globber",
                            Quantity = 8
                        },
                        new
                        {
                            Id = new Guid("59c48d4d-fad7-4d70-b5bd-79e7b41e37cb"),
                            CategoryId = new Guid("adbf2d17-62c6-44a7-a6d7-d09d510674c5"),
                            Description = "Guanti per sollevamento pesi.",
                            Image = "images/GuantiBuilder.jpg",
                            IsBestSeller = false,
                            Name = "Guanti Fitness Antiscivolo",
                            Price = 12.50m,
                            Producer = "Domyos",
                            Quantity = 35
                        },
                        new
                        {
                            Id = new Guid("a3e980f4-f4d1-4245-8cd1-2bf17e509ee6"),
                            CategoryId = new Guid("adbf2d17-62c6-44a7-a6d7-d09d510674c5"),
                            Description = "Pallone basket per esterni.",
                            Image = "images/PalloneBasket.jpg",
                            IsBestSeller = false,
                            Name = "Palla Basket Outdoor",
                            Price = 21.90m,
                            Producer = "Molten",
                            Quantity = 18
                        },
                        new
                        {
                            Id = new Guid("62b958ca-6bef-482f-bc20-2e915aa4ce94"),
                            CategoryId = new Guid("adbf2d17-62c6-44a7-a6d7-d09d510674c5"),
                            Description = "Cintura elastica regolabile con tasca.",
                            Image = "images/PortaCel.jpg",
                            IsBestSeller = false,
                            Name = "Cintura Running Porta Cellulare",
                            Price = 9.99m,
                            Producer = "Kalenji",
                            Quantity = 29
                        },
                        new
                        {
                            Id = new Guid("c62e92cf-bbcf-45e4-b005-5424ddcc6518"),
                            CategoryId = new Guid("adbf2d17-62c6-44a7-a6d7-d09d510674c5"),
                            Description = "Fascia per polso assorbente per lo sport.",
                            Image = "images/polsinonike.jpg",
                            IsBestSeller = false,
                            Name = "Fascia Polso Traspirante",
                            Price = 6.99m,
                            Producer = "Nike",
                            Quantity = 16
                        },
                        new
                        {
                            Id = new Guid("309d258d-5256-4799-8efe-ae975f282d38"),
                            CategoryId = new Guid("adbf2d17-62c6-44a7-a6d7-d09d510674c5"),
                            Description = "Fascia elastica per esercizi di tonificazione.",
                            Image = "images/SetElastici.jpg",
                            IsBestSeller = false,
                            Name = "Elastico Fitness Circolare",
                            Price = 4.90m,
                            Producer = "Decathlon",
                            Quantity = 40
                        },
                        new
                        {
                            Id = new Guid("26bf5eed-1c64-4628-8d2f-78eba724b441"),
                            CategoryId = new Guid("ab73a4ea-76fd-41cb-8a4d-4b0e9b610e38"),
                            Description = "Snack masticabili gusto manzo per cani adulti.",
                            Image = "images/SnackCani.jpg",
                            IsBestSeller = false,
                            Name = "Snack per Cani al Manzo",
                            Price = 2.90m,
                            Producer = "Pedigree",
                            Quantity = 40
                        },
                        new
                        {
                            Id = new Guid("7fa7ebfd-e136-46d8-889a-2b41cab07e19"),
                            CategoryId = new Guid("ab73a4ea-76fd-41cb-8a4d-4b0e9b610e38"),
                            Description = "Tiragraffi compatto per gatti cuccioli.",
                            Image = "images/Tiragraffi.jpg",
                            IsBestSeller = false,
                            Name = "Tiragraffi Mini",
                            Price = 12.99m,
                            Producer = "Trixie",
                            Quantity = 13
                        },
                        new
                        {
                            Id = new Guid("a080148f-a46f-4204-b9ba-57c011a6faf6"),
                            CategoryId = new Guid("ab73a4ea-76fd-41cb-8a4d-4b0e9b610e38"),
                            Description = "Ciotola per cibo e acqua, antiscivolo.",
                            Image = "images/CiotolaXcibo.jpg",
                            IsBestSeller = false,
                            Name = "Ciotola Doppia in Acciaio",
                            Price = 7.90m,
                            Producer = "Ferplast",
                            Quantity = 20
                        },
                        new
                        {
                            Id = new Guid("db33e815-7ecd-44e9-93a8-fcda641c9455"),
                            CategoryId = new Guid("ab73a4ea-76fd-41cb-8a4d-4b0e9b610e38"),
                            Description = "Guinzaglio per cani con estensione 5 metri.",
                            Image = "images/Guinzaglio.jpg",
                            IsBestSeller = false,
                            Name = "Guinzaglio Retrattile 5m",
                            Price = 14.50m,
                            Producer = "Flexi",
                            Quantity = 21
                        },
                        new
                        {
                            Id = new Guid("3674aaf0-5928-47ab-9afd-6deebfc5656f"),
                            CategoryId = new Guid("ab73a4ea-76fd-41cb-8a4d-4b0e9b610e38"),
                            Description = "Set spazzole e forbicine per la cura del pelo.",
                            Image = "images/SetSpazzoleForbicine.jpg",
                            IsBestSeller = false,
                            Name = "Set Toelettatura Base",
                            Price = 10.90m,
                            Producer = "Petkit",
                            Quantity = 15
                        });
                });

            modelBuilder.Entity("IBuy.API.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("IBuy.API.Models.CustomerDetails", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IBuy.API.Models.Product", b =>
                {
                    b.HasOne("IBuy.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("IBuy.API.Models.Transaction", b =>
                {
                    b.HasOne("IBuy.API.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IBuy.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
